/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jeremias
 */
public class jmlInicio extends javax.swing.JFrame {

    /**
     * Creates new form jmlInicio
     */
    public jmlInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        menu_principal = new javax.swing.JMenuBar();
        Alumno = new javax.swing.JMenu();
        AltaDeAlumnos = new javax.swing.JMenuItem();
        Materia = new javax.swing.JMenu();
        AltaDeMaterias = new javax.swing.JMenuItem();
        Inscripcion = new javax.swing.JMenu();
        FormularioDeInscripcion = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenu();
        Saliste = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        menu_principal.setToolTipText("");

        Alumno.setText("Alumno");

        AltaDeAlumnos.setText("Alta de alumnos");
        AltaDeAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaDeAlumnosActionPerformed(evt);
            }
        });
        Alumno.add(AltaDeAlumnos);

        menu_principal.add(Alumno);
        Alumno.getAccessibleContext().setAccessibleName("Alumnos");

        Materia.setText("Materia");

        AltaDeMaterias.setText("Alta de materias");
        AltaDeMaterias.setActionCommand("AgregarMateria");
        Materia.add(AltaDeMaterias);

        menu_principal.add(Materia);

        Inscripcion.setText("Inscripcion");

        FormularioDeInscripcion.setText("Formulario de Incripciones");
        Inscripcion.add(FormularioDeInscripcion);

        menu_principal.add(Inscripcion);

        salir.setText("Salir");

        Saliste.setText("Salir");
        salir.add(Saliste);

        menu_principal.add(salir);

        setJMenuBar(menu_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AltaDeAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaDeAlumnosActionPerformed
       //98498498498498498498
    }//GEN-LAST:event_AltaDeAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jmlInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jmlInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jmlInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jmlInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jmlInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AltaDeAlumnos;
    private javax.swing.JMenuItem AltaDeMaterias;
    private javax.swing.JMenu Alumno;
    private javax.swing.JMenuItem FormularioDeInscripcion;
    private javax.swing.JMenu Inscripcion;
    private javax.swing.JMenu Materia;
    private javax.swing.JMenuItem Saliste;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar menu_principal;
    private javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables
}
