
import MainPackage.Materia;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Jeremias
 */
public class VentanaMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifVentanaMateria
     */
    public VentanaMateria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AñoalquePertenece = new javax.swing.JLabel();
        CodigoMateria = new javax.swing.JTextField();
        NombreDeMateria = new javax.swing.JTextField();
        AnioPerteneceMateria = new javax.swing.JTextField();
        GuardarMateria = new javax.swing.JButton();
        NuevoMateria = new javax.swing.JButton();
        SalirMateria = new javax.swing.JButton();
        FormulariodeMaterias = new javax.swing.JLabel();
        Codigodemateria = new javax.swing.JLabel();
        NombredelaMateria = new javax.swing.JLabel();

        AñoalquePertenece.setText("Año al que pertenece:");

        CodigoMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoMateriaActionPerformed(evt);
            }
        });

        NombreDeMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreDeMateriaActionPerformed(evt);
            }
        });

        AnioPerteneceMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnioPerteneceMateriaActionPerformed(evt);
            }
        });

        GuardarMateria.setText("Guardar");
        GuardarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarMateriaActionPerformed(evt);
            }
        });

        NuevoMateria.setText("Nuevo");
        NuevoMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoMateriaActionPerformed(evt);
            }
        });

        SalirMateria.setText("Salir");
        SalirMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirMateriaActionPerformed(evt);
            }
        });

        FormulariodeMaterias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FormulariodeMaterias.setForeground(new java.awt.Color(51, 51, 51));
        FormulariodeMaterias.setText("Formulario de Materias");

        Codigodemateria.setText("Codigo de Materia:");

        NombredelaMateria.setText("Nombre de la Materia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(GuardarMateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NuevoMateria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SalirMateria))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(FormulariodeMaterias))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NombredelaMateria)
                                    .addComponent(Codigodemateria)
                                    .addComponent(AñoalquePertenece))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AnioPerteneceMateria)
                                    .addComponent(CodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreDeMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FormulariodeMaterias)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Codigodemateria)
                    .addComponent(CodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombredelaMateria)
                    .addComponent(NombreDeMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AñoalquePertenece)
                    .addComponent(AnioPerteneceMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarMateria)
                    .addComponent(NuevoMateria)
                    .addComponent(SalirMateria))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarMateriaActionPerformed
        try{
        if(!CodigoMateria.getText().isEmpty() && !NombreDeMateria.getText().isEmpty() && !AnioPerteneceMateria.getText().isEmpty()){
            Materia a = new Materia (Integer.parseInt(CodigoMateria.getText()),Integer.parseInt(AnioPerteneceMateria.getText()),NombreDeMateria.getText());
            jmlInicio.listaMaterias.add(a);
            JOptionPane.showMessageDialog(this, "Materia agregada con éxito", "Materia Agregada", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "No puede ingresar datos vacios", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El casillero Codigo y/o Año solo aceptan números", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_GuardarMateriaActionPerformed

    private void NuevoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoMateriaActionPerformed
        JOptionPane.showMessageDialog(this, "Limpiando casillas...", "Limpiando", JOptionPane.INFORMATION_MESSAGE);
        NombreDeMateria.setText("");
        CodigoMateria.setText("");
        AnioPerteneceMateria.setText("");
    }//GEN-LAST:event_NuevoMateriaActionPerformed

    private void SalirMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirMateriaActionPerformed
        this.dispose();
    }//GEN-LAST:event_SalirMateriaActionPerformed

    private void CodigoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoMateriaActionPerformed

    private void NombreDeMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreDeMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreDeMateriaActionPerformed

    private void AnioPerteneceMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnioPerteneceMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnioPerteneceMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnioPerteneceMateria;
    private javax.swing.JLabel AñoalquePertenece;
    private javax.swing.JTextField CodigoMateria;
    private javax.swing.JLabel Codigodemateria;
    private javax.swing.JLabel FormulariodeMaterias;
    private javax.swing.JButton GuardarMateria;
    private javax.swing.JTextField NombreDeMateria;
    private javax.swing.JLabel NombredelaMateria;
    private javax.swing.JButton NuevoMateria;
    private javax.swing.JButton SalirMateria;
    // End of variables declaration//GEN-END:variables
}
