/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Jeremias
 */
public class VentanaInscripcion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInscripcion
     */
    public VentanaInscripcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FormulariodeMaterias = new javax.swing.JLabel();
        ElijaunaMateria = new javax.swing.JLabel();
        ElijaunAlumno = new javax.swing.JLabel();
        InscribirAlumno = new javax.swing.JButton();
        SalirAlumno = new javax.swing.JButton();
        ElijaAlumnoBox = new javax.swing.JComboBox<>();
        ElijaMateriaBox = new javax.swing.JComboBox<>();

        setClosable(true);

        FormulariodeMaterias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FormulariodeMaterias.setForeground(new java.awt.Color(51, 51, 51));
        FormulariodeMaterias.setText("Formulario de Inscripcion");

        ElijaunaMateria.setText("Elija una Materia:");

        ElijaunAlumno.setText("Elija un Alumno:");

        InscribirAlumno.setText("Inscribir");
        InscribirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InscribirAlumnoActionPerformed(evt);
            }
        });

        SalirAlumno.setText("Salir");
        SalirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirAlumnoActionPerformed(evt);
            }
        });

        ElijaAlumnoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pibe 1", "Pibe 2", "Pibe 3", "Pibe 4" }));
        ElijaAlumnoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElijaAlumnoBoxActionPerformed(evt);
            }
        });

        ElijaMateriaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Web II", "Matematicas", "Laboratorio I" }));
        ElijaMateriaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElijaMateriaBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ElijaAlumnoBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ElijaMateriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(215, 215, 215)
                            .addComponent(InscribirAlumno)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                            .addComponent(SalirAlumno))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(96, 96, 96)
                                    .addComponent(FormulariodeMaterias))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ElijaunAlumno)
                                    .addComponent(ElijaunaMateria)))
                            .addGap(0, 105, Short.MAX_VALUE)))
                    .addGap(10, 10, 10)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(ElijaMateriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ElijaAlumnoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(FormulariodeMaterias)
                    .addGap(19, 19, 19)
                    .addComponent(ElijaunaMateria)
                    .addGap(18, 18, 18)
                    .addComponent(ElijaunAlumno)
                    .addGap(106, 106, 106)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(InscribirAlumno)
                        .addComponent(SalirAlumno))
                    .addContainerGap(34, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InscribirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscribirAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InscribirAlumnoActionPerformed

    private void SalirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirAlumnoActionPerformed

    private void ElijaMateriaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElijaMateriaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElijaMateriaBoxActionPerformed

    private void ElijaAlumnoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElijaAlumnoBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElijaAlumnoBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ElijaAlumnoBox;
    private javax.swing.JComboBox<String> ElijaMateriaBox;
    private javax.swing.JLabel ElijaunAlumno;
    private javax.swing.JLabel ElijaunaMateria;
    private javax.swing.JLabel FormulariodeMaterias;
    private javax.swing.JButton InscribirAlumno;
    private javax.swing.JButton SalirAlumno;
    // End of variables declaration//GEN-END:variables
}
