
import MainPackage.Alumno;
import MainPackage.Colegio;
import javax.swing.JOptionPane;

public class VentanaAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaAlumnos
     */
    public VentanaAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardarAlumno = new javax.swing.JButton();
        nuevoAlumno = new javax.swing.JButton();
        salirAlumno = new javax.swing.JButton();
        FormulariodeAlumnos = new javax.swing.JLabel();
        Legajo = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        ingreseLegajo = new javax.swing.JTextField();
        ingreseApellido = new javax.swing.JTextField();
        ingreseNombre = new javax.swing.JTextField();

        guardarAlumno.setText("Guardar");
        guardarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAlumnoActionPerformed(evt);
            }
        });

        nuevoAlumno.setText("Nuevo");
        nuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAlumnoActionPerformed(evt);
            }
        });

        salirAlumno.setText("Salir");
        salirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirAlumnoActionPerformed(evt);
            }
        });

        FormulariodeAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FormulariodeAlumnos.setForeground(new java.awt.Color(51, 51, 51));
        FormulariodeAlumnos.setText("Formulario de Alumnos");

        Legajo.setText("Legajo:");

        Apellido.setText("Apellido:");

        Nombre.setText("Nombre:");

        ingreseLegajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreseLegajoActionPerformed(evt);
            }
        });

        ingreseApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingreseApellidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(guardarAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nuevoAlumno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirAlumno))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Apellido)
                            .addComponent(Legajo)
                            .addComponent(Nombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FormulariodeAlumnos)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ingreseNombre)
                                .addComponent(ingreseApellido)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ingreseLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(FormulariodeAlumnos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Legajo)
                    .addComponent(ingreseLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellido)
                    .addComponent(ingreseApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(ingreseNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarAlumno)
                    .addComponent(nuevoAlumno)
                    .addComponent(salirAlumno))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAlumnoActionPerformed
        try{
            if(!ingreseLegajo.getText().isEmpty() && !ingreseApellido.getText().isEmpty() && !ingreseNombre.getText().isEmpty()){
                Alumno a = new Alumno(Integer.parseInt(ingreseLegajo.getText()),ingreseApellido.getText(),ingreseNombre.getText());
                jmlInicio.listaAlumnos.add(a);
                JOptionPane.showMessageDialog(this, "Alumno agregado con éxito", "Alumno Agregado", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "No puede ingresar datos vacios", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El casillero legajo solo acepta números", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarAlumnoActionPerformed

    private void nuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAlumnoActionPerformed
        JOptionPane.showMessageDialog(this, "Limpiando casillas...", "Limpiando", JOptionPane.INFORMATION_MESSAGE);
        ingreseLegajo.setText("");
        ingreseNombre.setText("");
        ingreseApellido.setText("");
    }//GEN-LAST:event_nuevoAlumnoActionPerformed

    private void salirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirAlumnoActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirAlumnoActionPerformed

    private void ingreseApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreseApellidoActionPerformed

    }//GEN-LAST:event_ingreseApellidoActionPerformed

    private void ingreseLegajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingreseLegajoActionPerformed
        
    }//GEN-LAST:event_ingreseLegajoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JLabel FormulariodeAlumnos;
    private javax.swing.JLabel Legajo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton guardarAlumno;
    private javax.swing.JTextField ingreseApellido;
    private javax.swing.JTextField ingreseLegajo;
    private javax.swing.JTextField ingreseNombre;
    private javax.swing.JButton nuevoAlumno;
    private javax.swing.JButton salirAlumno;
    // End of variables declaration//GEN-END:variables
}
